version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ~/.kube:/root/.kube
    ports:
      - 5000:5000
    command: ["bash", "-c", "uvicorn main:app --reload --port 5000 --host 0.0.0.0"]